version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: teebay
      POSTGRES_PASSWORD: teebay
      POSTGRES_DB: teebay_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
